### ISSUE TITLE
Invalid annotations data sent to GitHub

### ISSUE THREAD

**Issue by dorianmariefr** [standardrb/standard-ruby-action#1]
# Bug Report 

## Describe the bug

When the action runs on a pull request with annotations to send, it fails to send the annotations to GitHub.

# To Reproduce

Have a pull request with this file https://gist.github.com/dorianmariefr/471415385f653759b256dedd7ea059f7

# Expected behavior

Reports two errors:

```
  spec/policies/admin/trip_policy_spec.rb:5:57: Layout/SpaceInsideBlockBraces: Space missing inside }.
  spec/policies/admin/trip_policy_spec.rb:9:4: Layout/TrailingEmptyLines: Final newline missing.
```

## Stacktrace

```
/action/lib/github_client.rb:36:in `request_http': Unprocessable Entity: {"message":"Validation Failed","errors":[{"resource":"CheckRun","code":"invalid","field":"annotations"}],"documentation_url":"https://docs.github.com/rest/reference/checks#update-a-check-run"} (RuntimeError)
	from /action/lib/github_client.rb:10:in `patch'
	from /action/lib/github_check_run_service.rb:22:in `run'
	from /action/lib/index.rb:28:in `<main>'
```

## Action Version & Workflow File
 
 - Version v0.0.4

### Workflow File

```yaml
---
name: Lint with StandardRB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: StandardRB Linter
        uses: testdouble/standard-ruby-action@v0.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
