### ISSUE TITLE
Standard action Ruby version is different from application Ruby

### ISSUE THREAD

**Issue by willtcarey** [standardrb/standard-ruby-action#9]
# Bug Report 

## Describe the bug

Standardrb action reports different linting errors then we get locally because of Ruby version mismatches.

# To Reproduce

- Our app is configured to run in Ruby 2.7 (but could be 3.0, 3.1, etc)
- The standardrb action that Github Actions runs is hardcoded to be run from Ruby 3.2.2
	https://github.com/standardrb/standard-ruby-action/blob/f533e61f461ccb766b2d9c235abf59be02aea793/Dockerfile#L1

Locally we have code like the following which does not report a lint error.
```
def perform(*args)
  other_method(*args)
end
```

When standardrb runs in Github Actions this code does report a linting error because this violates Standard's rules in Ruby 3.2.

# Expected behavior

We expect to be able to run standardrb from the version of Ruby specified in our application so that the linting errors will match.

## Action Version & Workflow File
 
 - Version v0.0.5

### Workflow File

```yaml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: StandardRB Linter
        uses: standardrb/standard-ruby-action@v0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_BUNDLE_VERSION: true

```
